[core]
restore_state = true

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600

[spotify]
enabled = true
username = thomas.lawton@protonmail.com
password = 7eKK73mAAAxrnbp
client_id = 62b5a0eb-fbb3-489c-ba45-dce9905c9d78
client_secret = 1yF5TPERY-p3mxyptIY7LNHP6WMKr4dvCWRW80Styns=
bitrate = 320
